-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 18, 2022 at 11:39 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `movielaravel`
--

-- --------------------------------------------------------

--
-- Table structure for table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '2022_12_09_070807_add_role_as_to_users_table', 2),
(5, '2022_12_09_074007_create_movies_table', 3),
(6, '2022_12_12_165215_create_reviews_table', 4),
(7, '2022_12_14_153047_create_reviews_table', 5);

-- --------------------------------------------------------

--
-- Table structure for table `movies`
--

CREATE TABLE `movies` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `genre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `director` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `producer` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `writer` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `casts` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `summary` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `release_date` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image_path` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `movies`
--

INSERT INTO `movies` (`id`, `title`, `genre`, `director`, `producer`, `writer`, `casts`, `summary`, `release_date`, `image_path`, `created_at`, `updated_at`) VALUES
(1, 'Avatar 2', 'Action', 'James Cameron', 'James Cameron, Jon Landau', 'James Cameron', 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Michelle Rodriguez', 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.', 'December 18, 2009', '1670592028.jpg', '2022-12-09 01:03:58', '2022-12-09 05:20:28'),
(2, 'The School for Good and Evil', 'Fantasy', 'Paul Feig', 'Dina Amer, Karim Amer, and Elizabeth Woodward', 'David Magee, Paul Feig, and Soman Chainan', 'Sophia Anne Caruso, Sofia Wylie, Jamie Flatters, Charlize Theron, Kit Young, Kerry Washington, Michelle Yeoh, and Earl Cave', 'Best friends Sophie and Agatha find themselves on opposing sides of an epic battle when they\'re swept away into an enchanted school where aspiring heroes and villains are trained to protect the balance between good and evil.', 'October 19, 2022', '1670854155.jpg', '2022-12-12 06:08:49', '2022-12-12 06:09:15'),
(3, 'Purple Hearts', 'Romance', 'Elizabeth Allen and Rosenbaum', 'Amy Baer, Elysa Koplovitz Dutton, and Leslie Morgenstein', 'Liz W. Garcia and Kyle Jarrow', 'Sofia Carson, Nicholas Galitzine, Chosen Jacobs, John Harlan Kim, Kat Cunning, and Linden Ashby', 'An aspiring musician agrees to a marriage of convenience with a soon-to-deploy Marine, but a tragedy soon turns their fake relationship all too real.', 'July 29, 2022', '1670854288.jpg', '2022-12-12 06:11:28', '2022-12-12 06:11:28'),
(4, 'Knives Out', 'Mystery', 'Rian Johnson', 'Ram Bergman and Rian Johnson', 'Rian Johnson', 'Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis, Michael Shannon, Don Johnson, Toni Collette, LaKeith Stanfield, Katherine Langford, Jaeden Martell, and Christopher Plummer', 'The circumstances surrounding the death of crime novelist Harlan Thrombey are mysterious, but there\'s one thing that renowned Detective Benoit Blanc knows for sure -- everyone in the wildly dysfunctional Thrombey family is a suspect. Now, Blanc must sift through a web of lies and red herrings to uncover the truth.', 'November 27, 2019', '1670854398.jpg', '2022-12-12 06:13:18', '2022-12-12 06:13:18'),
(5, 'Truth or Dare', 'Horror', 'Jeff Wadlow', 'Jason Blum', 'Michael Reisz', 'Lucy Hale, Tyler Posey, Violett Beane, Hayden Szeto, and Landon Liboiron', 'Olivia, Lucas and a group of their college friends travel to Mexico for one last getaway before graduation. While there, a stranger convinces one of the students to play a seemingly harmless game of truth or dare with the others. Once the game starts, it awakens something evil -- a demon which forces the friends to share dark secrets and confront their deepest fears. The rules are simple but wicked -- tell the truth or die, do the dare or die, and if you stop playing, you die.', 'April 13, 2018', '1670854552.jpg', '2022-12-12 06:15:52', '2022-12-12 06:15:52'),
(6, 'The Tomorrow War', 'Adventure', 'Chris McKay', 'David Ellison, Dana Goldberg, Don Granger, Jules Daly, David S. Goyer, and Adam Kolbrenner', 'Zach Dean', 'Chris Pratt, Yvonne Strahovski, J. K. Simmons, Betty Gilpin, Sam Richardson, and Edwin Hodge', 'The world is stunned when a group of time travellers arrive from the year 2051 to deliver an urgent message: thirty years in the future, mankind is losing a global war against a deadly alien species.', 'July 2, 2021', '1670854632.jpg', '2022-12-12 06:17:12', '2022-12-12 06:17:12'),
(7, 'Scrooged', 'Comedy', 'Richard Donner', 'Richard Donner and Art Linson', 'Mitch Glazer and Michael O\'Donoghue', 'Bill Murray, Karen Allen, John Forsythe, and John Glover', 'A selfish, cynical television executive is haunted by three spirits bearing lessons on Christmas Eve. his home.', 'December 18, 2009', '1670854718.jpg', '2022-12-12 06:18:38', '2022-12-12 06:18:38'),
(8, 'Taxi Driver', 'Drama', 'Martin Scorsese', 'Michael Phillips and Julia Phillips', 'Paul Schrader', 'Robert De Niro, Jodie Foster, Cybill Shepherd, and Albert Brooks', 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.', 'February 9, 1976', '1670854784.jpg', '2022-12-12 06:19:44', '2022-12-12 06:19:44'),
(9, 'Identity', 'Thriller', 'James Mangold', 'Cathy Konrad', 'Michael Cooney', 'John Cusack, Ray Liotta, Amanda Peet, and John Hawkes', 'Stranded at a desolate Nevada motel during a nasty rain storm, ten strangers become acquainted with each other when they realize that they\'re being killed off one by one.', 'April 25, 2003', '1670854849.jpg', '2022-12-12 06:20:49', '2022-12-12 06:20:49'),
(10, 'Unforgiven', 'Western', 'Clint Eastwood', 'Clint Eastwood', 'David Webb Peoples', 'Clint Eastwood, Gene Hackman, Morgan Freeman, and Richard Harris', 'Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner Ned Logan and a young man, The \"Schofield Kid.\"', 'August 3, 1992', '1670855046.jpg', '2022-12-12 06:24:06', '2022-12-12 06:24:06'),
(11, 'Rainbow', 'Fantasy', 'Paco León', 'Sandra Hermida, Paco León, Álvaro Augustín, and Ghislain Barrois', 'Javier Gullón and Paco León', 'DORA, Carmen Maura, Carmen Machi, Áyax Pedrosa, Luis Bermejo, Wekaforé Jibril, Hovik Keuchkerian, and Cuentos Rosales', 'In search of her mother, a free-spirited teen and her eccentric companions set out on a whimsical journey while avoiding the clutches of a wicked woman.', 'September 30, 2022', '1670855133.jpg', '2022-12-12 06:25:33', '2022-12-12 06:25:33'),
(12, 'Mad Max: Fury Road', 'Action', 'George Miller', 'Doug Mitchell, George Miller, and PJ Voeten', 'George Miller, Brendan McCarthy, and Nico Lathouris', 'Tom Hardy, Charlize Theron, Nicholas Hoult, Hugh Keays-Byrne, Rosie Huntington-Whiteley, Riley Keough, Zoë Kravitz, Abbey Lee, and Courtney Eaton', 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.', 'May 7, 2015', '1670855198.jpg', '2022-12-12 06:26:38', '2022-12-12 06:26:38'),
(13, 'Se7en', 'Thriller', 'David Fincher', 'Arnold Kopelson and Phyllis Carlyle', 'Andrew Kevin Walker', 'John Travolta, Uma Thurman, Samuel L. Jackson, and Bruce Willis', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', 'September 15, 1995', '1670855252.jpg', '2022-12-12 06:27:32', '2022-12-12 06:27:32'),
(14, 'Sweet & Sour', 'Romance', 'Lee Gye-byeok', 'Park Se-joon', 'Kurumi Inui', 'Jang Ki-yong, Chae Soo-bin, and Krystal Jung', 'Faced with real-world opportunities and challenges, a couple endures the highs and lows of trying to make a long-distance relationship survive.', 'June 4, 2021', '1670855312.jpg', '2022-12-12 06:28:32', '2022-12-12 06:28:32'),
(15, 'The Girl With the Dragon Tattoo', 'Mystery', 'David Fincher', 'Scott Rudin, Ole Søndberg, , Søren Stærmose, and Ceán Chaffin', 'Stieg Larsson', 'Daniel Craig, Rooney Mara, Christopher Plummer, Stellan Skarsgård, Steven Berkoff, Robin Wright, Yorick van Wageningen, and Joely Richardson', 'Disgraced financial reporter Mikael Blomkvist (Daniel Craig) finds a chance to redeem his honor after being hired by wealthy Swedish industrialist Henrik Vanger (Christopher Plummer) to solve the 40-year-old murder of Vanger\'s niece, Harriet. Vanger believes that Harriet was killed by a member of his own family. Eventually joining Blomkvist on his dangerous quest for the truth is Lisbeth Salander (Rooney Mara), an unusual but ingenious investigator whose fragile trust is not easily won.', 'December 21, 2011', '1670855410.jpg', '2022-12-12 06:30:10', '2022-12-12 06:32:01'),
(16, 'The Nun', 'Horror', 'Corin Hardy', 'Peter Safran and James Wan', 'James Wan and Gary Dauberman', 'Demián Bichir, Taissa Farmiga, and Jonas Bloquet', 'When a young nun at a cloistered abbey in Romania takes her own life, a priest with a haunted past and a novitiate on the threshold of her final vows are sent by the Vatican to investigate. Together, they uncover the order\'s unholy secret. Risking not only their lives but their faith and their very souls, they confront a malevolent force in the form of a demonic nun.', 'September 7, 2018', '1670855594.jpg', '2022-12-12 06:33:14', '2022-12-12 06:33:14'),
(17, 'Dune', 'Adventure', 'Denis Villeneuve', 'Mary Parent, Denis Villeneuve, Cale Boyter, and Joe Caracciolo Jr.', 'Frank Herbert', 'Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Josh Brolin, Stellan Skarsgård, Dave Bautista, Stephen McKinley Henderson, Zendaya, Chang Chen, Charlotte Rampling, Jason Momoa, and Javier Bardem', 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet\'s exclusive supply of the most precious resource in existence, only those who can conquer their own fear will survive.', 'October 22, 2021', '1670855699.jpg', '2022-12-12 06:34:59', '2022-12-12 06:34:59'),
(18, 'The Searchers', 'Western', 'John Ford', 'C.V. Whitney Pictures', 'Frank S. Nugent', 'John Wayne, Jeffrey Hunter, Vera Miles, and Ward Bond', 'An American Civil War veteran embarks on a years-long journey to rescue his niece from the Comanches after the rest of his brother\'s family is massacred in a raid on their Texas farm.', 'May 16, 1956', '1670855805.jpg', '2022-12-12 06:36:45', '2022-12-12 06:36:45'),
(19, 'Pulp Fiction', 'Drama', 'Quentin Tarantino', 'Lawrence Bender', 'Quentin Tarantino', 'John Travolta, Uma Thurman, Samuel L. Jackson, and Bruce Willis', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'May 21, 1994', '1670855878.jpg', '2022-12-12 06:37:58', '2022-12-12 06:37:58'),
(20, 'The Godfather', 'Drama', 'Francis Ford Coppola', 'Albert S. Ruddy', 'Mario Puzo and Francis Ford Coppola', 'Marlon Brando, Al Pacino, James Caan, and Diane Keaton', 'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.', 'March 14, 1972', '1670855923.jpg', '2022-12-12 06:38:43', '2022-12-12 06:38:43'),
(21, 'Groundhog Day', 'Comedy', 'Harold Ramis', 'Trevor Albert and Harold Ramis', 'Danny Rubin and Harold Ramis', 'Bill Murray, Andie MacDowell, Chris Elliott, and Stephen Tobolowsky', 'A narcissistic, self-centered weatherman finds himself in a time loop on Groundhog Day, and the day keeps repeating until he gets it right.', 'February 12, 1993', '1670855978.jpg', '2022-12-12 06:39:38', '2022-12-12 06:39:38'),
(22, 'Through My Window', 'Romance', 'Marçal Forès', 'Núria Valls and Adrián Guerra', 'Ariana Godoy', 'Julio Peña, Clara Galle, and Pilar Castro', 'Raquel has a longtime crush on her hot neighbour, Ares, whom she secretly watches but has never spoken to. Can she make Ares fall in love with her?', 'February 4, 2022', '1670856056.jpg', '2022-12-12 06:40:56', '2022-12-12 06:40:56'),
(23, 'After', 'Romance', 'Jenny Gage', 'Jennifer Gibgot, Courtney Solomon, Mark Canton, Aron Levitz, Anna Todd , Meadow Williams, and Dennis Pelino', 'Anna Todd', 'Josephine Langford, Hero Fiennes Tiffin, Selma Blair, Inanna Sarkis, Shane Paul McGhie, Pia Mia, Khadijha Red Thunder, Dylan Arnold, Samuel Larsen, Jennifer Beals, and Peter Gallagher', 'A young woman falls for a guy with a dark secret and the two embark on a rocky relationship. Based on the novel by Anna Todd.', 'April 12, 2019', '1670856147.jpg', '2022-12-12 06:42:27', '2022-12-12 06:42:27'),
(24, 'Before I Go to Sleep', 'Mystery', 'Rowan Joffé', 'Avi Lerner, Liza Marshall, Mark Gill, Matthew O\'Toole, and Ridley Scott', 'Rowan Joffé', 'Nicole Kidman, Mark Strong, Colin Firth, and Anne-Marie Duff', 'Ever since a vicious attack nearly claimed her life, Christine Lucas (Nicole Kidman) has suffered from anterograde amnesia and is unable to form new memories. Every morning, she becomes reacquainted with her husband, Ben (Colin Firth), and the other constants in her life. In accordance with her doctor\'s (Mark Strong) instructions, Christine keeps a video diary. As Christine starts to uncover terrifying truths about her past, she begins to question everything -- and everyone -- around her.', 'September 5, 2014', '1670856217.jpg', '2022-12-12 06:43:37', '2022-12-12 06:43:37'),
(25, 'Fullmetal Alchemist', 'Fantasy', 'Fumihiko Sori', 'Yumihiko Yoshihara', 'Hiromu Arakawa', 'Ryosuke Yamada, Tsubasa Honda, Dean Fujioka, Ryuta Sato, Jun Kunimura, Fumiyo Kohinata, Yasuko Matsuyuki', 'The Elric brothers’ long and winding journey comes to a close in this epic finale, where they must face off against an unworldly, nationwide threat.', 'September 24, 2022', '1670950689.jpg', '2022-12-13 09:58:09', '2022-12-13 09:58:55'),
(26, 'If I Stay', 'Romance', 'R. J. Cutler', 'Alison Greenspan', 'Gayle Forman', 'Chloë Grace Moretz, Mireille Enos, Joshua Leonard, Stacy Keach', 'Mia Hall (Chloë Grace Moretz), a talented young cellist, thought the most difficult decision she would ever have to make would be whether to pursue her musical dreams at prestigious Juilliard or follow her heart to be with the love of her life, Adam (Jamie Blackley), a rock singer/guitarist. However, a car wreck changes everything in an instant, and now Mia\'s life hangs in the balance. Suspended between life and death, Mia faces a choice that will decide her future.', 'August 18, 2014', '1670953619.jpg', '2022-12-13 10:46:59', '2022-12-13 10:46:59'),
(27, 'The Girl on the Train', 'Mystery', 'Tate Taylor', 'Marc Platt, Jared LeBoff', 'Paula Hawkins', 'Emily Blunt, Rebecca Ferguson, Haley Bennett, Justin Theroux, Luke Evans, Allison Janney', 'Commuter Rachel Watson (Emily Blunt) catches daily glimpses of a seemingly perfect couple, Scott and Megan, from the window of her train. One day, Watson witnesses something shocking unfold in the backyard of the strangers\' home. Rachel tells the authorities what she thinks she saw after learning that Megan is now missing and feared dead. Unable to trust her own memory, the troubled woman begins her own investigation, while police suspect that Rachel may have crossed a dangerous line.', 'October 7, 2016', '1670953799.jpg', '2022-12-13 10:49:59', '2022-12-13 10:50:26'),
(28, 'Eerie', 'Horror', 'Mikhail Red', 'Carlo Katigbak, Malou N. Santos, Olivia Lamasan, Abhi Rastogi, Gin Kai Chan, Justin Deimen', 'Mikhail Red, Rae Red, Mariah Reodica', 'Carlo Katigbak, Malou N. Santos, Olivia Lamasan, Abhi Rastogi, Gin Kai Chan, Justin Deimen', 'Eerie A guidance counsellor\'s special talents help her unravel the mystery behind the unexpected and gruesome death of a student at a Catholic school for girls.', 'March 27, 2019', '1670953952.jpg', '2022-12-13 10:52:32', '2022-12-13 10:52:32'),
(29, 'Mortal Kombat', 'Adventure', 'Simon McQuoid', 'James Wan, Todd Garner, Simon McQuoid, E. Bennett Walsh', 'Oren Uziel, Greg Russo', 'Lewis Tan, Jessica McNamee, Josh Lawson, Tadanobu Asano, Mehcad Brooks, Ludi Lin, Chin Han, Joe Taslim, Hiroyuki Sanada,', 'Hunted by the fearsome warrior Sub-Zero, MMA fighter Cole Young finds sanctuary at the temple of Lord Raiden. Training with experienced fighters Liu Kang, Kung Lao and the rogue mercenary Kano, Cole prepares to stand with Earth\'s greatest champions to take on the enemies from Outworld in a high-stakes battle for the universe.', 'April 23, 2021', '1670954108.jpg', '2022-12-13 10:55:08', '2022-12-13 10:55:08'),
(30, 'Three Thousand Years of Longing', 'Fantasy', 'Jon Watts', 'Kevin Feige, Amy Pascal', 'Chris McKenna, Erik Sommers', 'Tom Holland , Zendaya Benedict, Cumberbatch Jacob, Batalon Jon, Favreau Jamie, Foxx Willem, Dafoe Alfred, Molina Benedict, Wong Tony, Revolori Marisa, Tomei Andrew, Garfield Tobey Maguire', 'With Spider-Man\'s identity now revealed, our friendly neighborhood web-slinger is unmasked and no longer able to separate his normal life as Peter Parker from the high stakes of being a superhero. When Peter asks for help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.', 'December 17, 2021', '1670969363.jpg', '2022-12-13 15:09:23', '2022-12-13 15:09:23'),
(31, 'The Vow', 'Romance', 'Michael Sucsy', 'Roger Birnbaum, Gary Barber, Jonathan Glickman, Paul Taublieb', 'Stuart Sender', 'Rachel McAdams, Channing Tatum, Sam Neill, Scott Speedman, Jessica Lange, Jessica McNamee', 'Paige (Rachel McAdams) and Leo (Channing Tatum) are happily married newlyweds, but their idyllic life together suddenly shatters when a car accident leaves her in a coma. When Paige awakes, she has severe memory loss and doesn\'t know Leo. She also has a confusing relationship with her parents (Sam Neill, Jessica Lange) and still harbors feelings for a former fiance (Scott Speedman). Despite these difficult obstacles, Leo is determined to renew their bond and rebuild their marriage.', 'February 10, 2012', '1670969847.jpg', '2022-12-13 15:17:27', '2022-12-13 15:17:27'),
(32, 'Arrival', 'Mystery', 'Denis Villeneuve', 'Shawn Levy, Dan Levine, Aaron Ryder, David Linde', 'Ted Chiang', 'Amy Adams, Jeremy Renner, Forest Whitaker, Michael Stuhlbarg, Tzi Ma', 'Linguistics professor Louise Banks (Amy Adams) leads an elite team of investigators when gigantic spaceships touch down in 12 locations around the world. As nations teeter on the verge of global war, Banks and her crew must race against time to find a way to communicate with the extraterrestrial visitors. Hoping to unravel the mystery, she takes a chance that could threaten her life and quite possibly all of mankind.', 'November 11, 2016', '1670970204.jpg', '2022-12-13 15:23:24', '2022-12-13 15:23:24'),
(33, 'Army of the Dead', 'Horror', 'Louis Leterrier', 'Alex Kurtzman, Roberto Orci, Bobby Cohen', 'oaz Yakin, Edward Ricourt', 'Mark Ruffalo, Woody Harrelson, Mélanie Laurent, Isla Fisher, Dave Franco, Common Michael, Caine Morgan Freeman', 'Charismatic magician Atlas (Jesse Eisenberg) leads a team of talented illusionists called the Four Horsemen. Atlas and his comrades mesmerize audiences with a pair of amazing magic shows that drain the bank accounts of the corrupt and funnel the money to audience members. A federal agent (Mark Ruffalo) and an Interpol detective (Mélanie Laurent) intend to rein in the Horsemen before their next caper, and they turn to Thaddeus (Morgan Freeman), a famous debunker, for help.', 'May 31, 2013', '1670970453.jpg', '2022-12-13 15:27:33', '2022-12-13 15:27:33'),
(34, 'Spider-Man; No Way Home', 'Adventure', 'Jon Watts', 'Kevin Feige, Amy Pascal', 'Chris McKenna, Erik Sommers', 'Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon', 'With Spider-Man\'s identity now revealed, our friendly neighborhood web-slinger is unmasked and no longer able to separate his normal life as Peter Parker from the high stakes of being a superhero. When Peter asks for help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.', 'December 17, 2021', '1670970905.jpg', '2022-12-13 15:35:05', '2022-12-13 15:35:05'),
(35, 'Alienoid', 'Fantasy', 'Choi Dong-hoon', 'Ahn Soo-Hyun', 'Choi Dong-hoon', 'Ryu Jun-yeol, Kim Woo-bin, Kim Tae-ri, So Ji-sub, Yum Jung-ah', 'Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human\'s body. The two parties cross paths when a time-traveling portal opens up.', 'August 26, 2022', '1670971127.jpg', '2022-12-13 15:38:47', '2022-12-13 15:38:47'),
(36, 'All My Life', 'Romance', 'Marc Meyers', 'Todd Garner, Sean Robins', 'Todd Rosenberg', 'Jessica Rothe, Harry Shum Jr., Marielle Scott ,Kyle Allen, Jay Pharoah', 'Jennifer Carter and Solomon Chau are a sweet, fun-loving, newly engaged couple who are ready to start their lives together. But when Solomon is diagnosed with terminal liver cancer, their hopes for a summer wedding become impossible. With time running out, their friends and families soon devise an inspirational plan to help Jennifer and Solomon realize their dream wedding.', 'December 4, 2020', '1670971218.jpg', '2022-12-13 15:40:18', '2022-12-13 15:40:18'),
(37, 'Now You See Me', 'Mystery', 'Louis Leterrier', 'Alex Kurtzman, Roberto Orci, Bobby Cohen', 'Boaz Yakin, Edward Ricourt', 'Jesse Eisenberg, Mark Ruffalo, Woody Harrelso, Mélanie Laurent, Isla Fisher, Dave Franco', 'Charismatic magician Atlas (Jesse Eisenberg) leads a team of talented illusionists called the Four Horsemen. Atlas and his comrades mesmerize audiences with a pair of amazing magic shows that drain the bank accounts of the corrupt and funnel the money to audience members. A federal agent (Mark Ruffalo) and an Interpol detective (Mélanie Laurent) intend to rein in the Horsemen before their next caper, and they turn to Thaddeus (Morgan Freeman), a famous debunker, for help.', 'May 31, 2013', '1670971342.jpg', '2022-12-13 15:42:22', '2022-12-13 15:42:22'),
(38, 'The Devine Fury', 'Horror', 'Kim Joo-hwan', 'Park Ah-Hyeoung, Im Jeon-Hyeok', 'Kim Joo-hwan', 'Park Seo-joon Ahn, Sung-ki Woo, Do-hwan, Park Ji-hyun', 'After waking up with mysterious wounds on his hands, a champion MMA fighter finds himself in an otherworldly battle against evil forces wreaking havoc in the human world.', 'July 31, 2019', '1670971445.jpg', '2022-12-13 15:44:05', '2022-12-13 15:44:05'),
(39, 'F9', 'Adventure', 'Justin Lin', 'Neal H. Morit, Vin Diesel, Justin Lin, Jeffrey Kirschenbaum, Joe Roth, Clayton Townsend, Samantha Vincent', 'Justin Lin, Alfredo Botello, Daniel Casey', 'Vin Diesel, Michelle Rodriguez, Tyrese Gibson, Chris \"Ludacris\" Bridges, John Cena', 'Dom Toretto is living the quiet life off the grid with Letty and his son, but they know that danger always lurks just over the peaceful horizon. This time, that threat forces Dom to confront the sins of his past to save those he loves most. His crew soon comes together to stop a world-shattering plot by the most skilled assassin and high-performance driver they\'ve ever encountered -- Dom\'s forsaken brother.', 'June 25, 2021', '1670971842.jpg', '2022-12-13 15:50:42', '2022-12-13 15:50:42'),
(40, 'Glorious', 'Fantasy', 'Rebekah McKendry', 'Bob Portal, Inderpal Singh, Joe Wicker, Morgan Peter Brown, Jason Scott Goldberg, Christian Armogida', 'Todd Rigney', 'Ryan Kwanten, J. K. Simmons', 'After a breakup, Wes ends up at a remote rest stop. He finds himself locked inside the bathroom with a mysterious figure speaking from an adjacent stall. Soon Wes realizes he is involved in a situation more terrible than he could imagine.', 'August 18, 2022', '1670971924.jpg', '2022-12-13 15:52:04', '2022-12-13 15:52:04'),
(41, 'Five Feet Apart', 'Romance', 'Justin Baldoni', 'Cathy Schulman, Justin Baldoni, Christopher H. Warner', 'Mikki Daughtry, Tobias Iaconis', 'Haley Lu Richardson, Cole Sprouse', 'Seventeen-year-old Stella spends most of her time in the hospital as a cystic fibrosis patient. Her life is full of routines, boundaries and self-control -- all of which get put to the test when she meets Will, an impossibly charming teen who has the same illness. There\'s an instant flirtation, though restrictions dictate that they must maintain a safe distance between them. As their connection intensifies, so does the temptation to throw the rules out the window and embrace that attraction.', 'March 15, 2019', '1670972028.jpg', '2022-12-13 15:53:48', '2022-12-13 15:53:48'),
(42, 'I Still See You', 'Mystery', 'Scott Speer', 'Paul Brooks, Leon Clarance', 'Jason Fuchs', 'Bella Thorne, Richard Harmon, Dermot Mulroney', 'After a cataclysmic event leaves the world haunted by ghost-like spectres called `Remnants\', a high school student is stalked by an angry, violent Remnant who wants to kill her.', 'October 12, 2018', '1670972181.jpg', '2022-12-13 15:56:21', '2022-12-13 15:56:21'),
(43, 'Slender Man', 'Mystery', 'Mike Barker', 'Bruna Papandrea, Jeanne Snow, Erik Feig, Lucy Kitada, Mila Kunis', 'Jessica Knoll', 'Mila Kunis', 'A writer\'s perfectly crafted New York City life starts to unravel when a true-crime documentary forces her to confront her harrowing high school history and question the choices she made as a teenager.', 'October 7, 2022', '1670972288.jpg', '2022-12-13 15:58:08', '2022-12-13 15:58:08'),
(44, 'The Curse of La Llorona', 'Horror', 'Michael Chaves', 'James Wan, Gary Dauberman, Emile Gladstone', 'Mikki Daughtry, Tobias Iaconis', 'Linda Cardellini, Raymond Cruz, Patricia Velásquez', 'In 1970s Los Angeles, the legendary ghost La Llorona is stalking the night -- and the children. Ignoring the eerie warning of a troubled mother, a social worker and her own kids are drawn into a frightening supernatural realm. Their only hope of surviving La Llorona\'s deadly wrath is a disillusioned priest who practices mysticism to keep evil at bay.', 'April 19, 2019', '1670972387.jpg', '2022-12-13 15:59:47', '2022-12-13 15:59:47'),
(45, 'Bloodshot', 'Adventure', 'David S. F. Wilson', 'Neal H. Moritz, Toby Jaffe, Dinesh Shamdasani, Vin Diesel', 'Jeff Wadlow', 'Vin Diesel, Eiza González, Sam Heughan, Toby Kebbell, Guy Pearce', 'After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine - Bloodshot. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there\'s more to the conspiracy than he thought.', 'March 13, 2020', '1670972478.jpg', '2022-12-13 16:01:18', '2022-12-13 16:01:18'),
(46, 'Thor: Love and Thunder', 'Fantasy', 'Taika Waititi', 'Taika Waititi', 'Taika Waititi, Jennifer Kaytin Robinson', 'Chris Hemsworth, Christian Bale, Tessa Thompson, Jaimie Alexander, Taika Waititi', 'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.', 'July 8, 2022', '1670973431.jpg', '2022-12-13 16:17:11', '2022-12-13 16:17:11'),
(47, 'All Bright Places', 'Romance', 'Brett Haley', 'Paula Mazur, Mitchell Kaplan, Elle Fanning, Brittany Kahan-Ward, Doug Mankoff, Andrew Spaulding', 'Jennifer Niven', 'Elle Fanning, Justice Smith, Alexandra Shipp, Kelli O\'Hara, Lamar Johnson', 'After meeting each other, two teenagers struggle with the emotional and physical scars of their pasts. They discover that even the smallest moments can mean something.', 'February 28, 2020', '1670973520.jpg', '2022-12-13 16:18:40', '2022-12-13 16:18:40'),
(48, 'Recalled', 'Mystery', 'Seo Yoo-min', 'Jeong Hye-on', 'Seo Yoo-min', 'Seo Yea-ji Kim, Kang-woo', 'Sujin, who lost her memories due to a horrible incident, starts suspecting her husband. She is confused between reality and illusion, truth and lies.', 'April 21, 2021', '1670973596.jpg', '2022-12-13 16:19:56', '2022-12-13 16:19:56'),
(49, 'The Invisible Man', 'Horror', 'Leigh Whannell', 'Jason Blum, Kylie du Fresne', 'Leigh Whannell', 'Elisabeth Moss, Aldis Hodge, Storm Reid, Harriet Dyer', 'After staging his own suicide, a crazed scientist uses his power to become invisible to stalk and terrorize his ex-girlfriend. When the police refuse to believe her story, she decides to take matters into her own hands and fight back.', 'February 28, 2020', '1670973728.jpg', '2022-12-13 16:22:08', '2022-12-13 16:22:08'),
(50, 'The Batman', 'Adventure', 'Matt Reeves', 'Dylan Clark, Matt Reeves', 'Matt Reeves, Peter Craig', 'Robert Pattinson, Zoë Kravitz, Paul Dano, Jeffrey Wright, John Turturro', 'Batman ventures into Gotham City\'s underworld when a sadistic killer leaves behind a trail of cryptic clues. As the evidence begins to lead closer to home and the scale of the perpetrator\'s plans become clear, he must forge new relationships, unmask the culprit and bring justice to the abuse of power and corruption that has long plagued the metropolis.', 'March 4, 2022', '1670973853.jpg', '2022-12-13 16:24:13', '2022-12-13 16:24:13'),
(51, 'The Lost Girls', 'Fantasy', 'Livia De Paolis', 'Chris Curling, Meta Valentic, Sam Tipper-Hale, Peter Touche, Livia De Paolis', 'Livia De Paolis', 'Livia De Paolis, Ella-Rae Smith, Julian Ovenden, Parker Sawyers, Louis Partridge', 'The Lost Girls chronicles four generations of Darling women as they struggle in the aftermath of their adventures with Peter Pan (Louis Partridge) in Neverland. Like her grandmother (Vanessa Redgrave) and her mother Jane (Joely Richardson) before her, Wendy (Emily Carey and Livia De Paolis) must escape Pan’s hold on her and the promise he desperately wants her to keep. As her daughter Berry (Ella Rae-Smith) comes into Peter’s orbit, Wendy must fight to save her relationship with her daughter while reconciling her legacy.', 'June 17, 2022', '1670973977.jpg', '2022-12-13 16:26:17', '2022-12-13 16:26:17'),
(52, 'Titanic', 'Romance', 'James Cameron', 'James Cameron, Jon Landau', 'James Cameron', 'Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates, Frances Fisher', 'James Cameron\'s \"Titanic\" is an epic, action-packed romance set against the ill-fated maiden voyage of the R.M.S. Titanic; the pride and joy of the White Star Line and, at the time, the largest moving object ever built. She was the most luxurious liner of her era -- the \"ship of dreams\" -- which ultimately carried over 1,500 people to their death in the ice cold waters of the North Atlantic in the early hours of April 15, 1912.', 'December 19, 1997', '1670974064.jpg', '2022-12-13 16:27:44', '2022-12-13 16:27:44'),
(53, 'Reminiscence', 'Mystery', 'Lisa Joy', 'Lisa Joy, Jonathan Nolan, Michael De Luca, Aaron Ryder', 'Lisa Joy', 'Hugh Jackman, Rebecca Ferguson, Thandiwe Newton, Cliff Curtis', 'Nick Bannister, a private investigator of the mind, navigates the darkly alluring world of the past by helping his clients access lost memories. Living on the fringes of the sunken Miami coast, his life is forever changed as he uncovers a violent conspiracy while trying to solve the mystery behind a client who disappeared.', 'August 20, 2021', '1670974209.jpg', '2022-12-13 16:30:09', '2022-12-13 16:30:09'),
(54, 'A Quiet Place', 'Horror', 'John Krasinski', 'Michael Bay, Andrew Form, Brad Fuller', 'Bryan Woods, Scott Beck', 'Emily Blunt, John Krasinski', 'If they hear you, they hunt you. A family must live in silence to avoid mysterious creatures that hunt by sound. Knowing that even the slightest whisper or footstep can bring death, Evelyn and Lee are determined to find a way to protect their children while desperately searching for a way to fight back.', 'April 6, 2018', '1670974278.jpg', '2022-12-13 16:31:18', '2022-12-13 16:31:18'),
(55, 'The Great Wall', 'Adventure', 'Zhang Yimou', 'Thomas Tull, Charles Roven, Jon Jashni, Peter Loehr', 'Max Brooks, Edward Zwick, Marshall Herskovitz', 'Matt Damon, Jing Tian, Pedro Pascal, Willem Dafoe, Andy Lau', 'When a mercenary warrior (Matt Damon) is imprisoned within the Great Wall, he discovers the mystery behind one of the greatest wonders of the world. As wave after wave of marauding beasts besiege the massive structure, his quest for fortune turns into a journey toward heroism as he joins a huge army of elite warriors to confront the unimaginable and seemingly unstoppable force.', 'February 17, 2017', '1670974370.jpg', '2022-12-13 16:32:50', '2022-12-13 16:32:50'),
(56, 'Morbius', 'Fantasy', 'Daniel Espinosa', 'Avi Arad, Matt Tolmach, Lucas Foster', 'Matt Sazama, 	Burk Sharpless', 'Jared Leto, Matt Smith, Adria Arjona, Jared Harris, Al Madrigal', 'One of the most compelling and conflicted characters in Sony Pictures Universe of Marvel Characters comes to the big screen as Oscar® winner Jared Leto transforms into the enigmatic antihero Michael Morbius. Dangerously ill with a rare blood disorder and determined to save others suffering his same fate, Dr. Morbius attempts a desperate gamble. While at first it seems to be a radical success, a darkness inside him is unleashed. Will good override evil – or will Morbius succumb to his mysterious new urges?', 'April 1, 2022', '1670974470.jpg', '2022-12-13 16:34:30', '2022-12-13 16:34:30'),
(57, 'The Handmaiden', 'Romance', 'Park Chan-wook', 'Park Chan-wook, Syd Lim', 'Park Chan-wook, Jeong Seo-kyeong', 'Kim Min-hee, Kim Tae-ri, Ha Jung-woo, Cho Jin-woong', 'With help from an orphaned pickpocket (Kim Tae-ri), a Korean con man (Ha Jung-woo) devises an elaborate plot to seduce and bilk a Japanese woman (Kim Min-hee) out of her inheritance.', 'June 1, 2016', '1670974576.jpg', '2022-12-13 16:36:16', '2022-12-13 16:36:16'),
(58, 'Calls', 'Mystery', 'J. Sabarish', 'S. Jayakumar', 'J. Sabarish', 'V. J. Chitra, Vinodhini Devadarshini, R. Sundarrajan', 'Told through a series of interconnected phone conversations, these conversations chronicle the mysterious story of a group of strangers whose lives are thrown into disarray in the lead-up to an apocalyptic event.', 'February 26, 2002', '1670974723.jpg', '2022-12-13 16:38:43', '2022-12-13 16:38:43'),
(59, 'Halloween Kills', 'Horror', 'David Gordon Green', 'Malek Akkad, Jason Blum, Bill Block', 'Scott Teems, Danny McBride, David Gordon Green', 'Jamie Lee Curtis, Judy Greer, Andi Matichak, Will Patton, Thomas Mann', 'The nightmare isn\'t over as unstoppable killer Michael Myers escapes from Laurie Strode\'s trap to continue his ritual bloodbath. Injured and taken to the hospital, Laurie reunites with Tommy Doyle, the boy she was babysitting on the night Michael began his reign of terror. As Laurie continues to fight through the pain, Tommy leads an angry mob of vigilantes to rise up against Myers and destroy the evil once and for all.', 'October 15, 2022', '1670974844.jpg', '2022-12-13 16:40:44', '2022-12-13 16:40:44'),
(60, 'Pan', 'Adventure', 'Joe Wright', 'Greg Berlanti, Sarah Schechter, Paul Webster', 'Jason Fuchs', 'Hugh Jackman, Garrett Hedlund, Rooney Mara, Levi Miller, Amanda Seyfried', 'Living a bleak existence at a London orphanage, 12-year-old Peter (Levi Miller) finds himself whisked away to the fantastical world of Neverland. Adventure awaits as he meets new friend James Hook (Garrett Hedlund) and the warrior Tiger Lily (Rooney Mara). They must band together to save Neverland from the ruthless pirate Blackbeard (Hugh Jackman). Along the way, the rebellious and mischievous boy discovers his true destiny, becoming the hero forever known as Peter Pan.', 'October 9, 2015', '1670974953.jpg', '2022-12-13 16:42:33', '2022-12-13 16:42:33'),
(61, 'Fistful of Vengeance', 'Fantasy', 'Roel Reiné', 'Doug Mitchell, George Miller', 'Cameron Litvack, Jessica Chou, Yalun Tu', 'Iko Uwais, Lewis Tan, Lawrence Kao, Pearl Thusi, Francesca Corney', 'A revenge mission becomes a fight to save the world from an ancient threat when superpowered assassin Kai tracks a killer to Bangkok.', 'February 17, 2022', '1670975135.jpg', '2022-12-13 16:45:35', '2022-12-13 16:45:35'),
(62, 'Eternal Sunshine of the Spotless Mind', 'Romance', 'Michel Gondry', 'Steve Golin, Anthony Bregman', 'Charlie Kaufman, Michel Gondry, Pierre Bismuth', 'Jim Carrey, Kate Winslet, Kirsten Dunst, Mark Ruffalo', 'After a painful breakup, Clementine (Kate Winslet) undergoes a procedure to erase memories of her former boyfriend Joel (Jim Carrey) from her mind. When Joel discovers that Clementine is going to extremes to forget their relationship, he undergoes the same procedure and slowly begins to forget the woman that he loved. Directed by former music video director Michel Gondry, the visually arresting film explores the intricacy of relationships and the pain of loss.', 'March 19, 2004', '1670975254.jpg', '2022-12-13 16:47:34', '2022-12-13 16:47:34'),
(63, 'Enola Holmes', 'Mystery', 'Harry Bradbeer', 'Mary Parent, Alex Garcia, Ali Mendes, Millie Bobby Brown, Paige Brown', 'Nancy Springer', 'Millie Bobby, Brown Sam, Claflin Henry, Cavill Helena, Bonham Carter', 'While searching for her missing mother, intrepid teen Enola Holmes uses her sleuthing skills to outsmart big brother Sherlock and help a runaway lord.', 'September 23, 2020', '1670975395.jpg', '2022-12-13 16:49:55', '2022-12-13 16:49:55'),
(64, 'Us', 'Horror', 'Jordan Peele', 'Jason Blum, Ian Cooper, Sean McKittrick, Jordan Peele', 'Jordan Peele', 'Lupita Nyong\'o, Winston Duke, Elisabeth Moss, Tim Heidecker', 'Accompanied by her husband, son and daughter, Adelaide Wilson returns to the beachfront home where she grew up as a child. Haunted by a traumatic experience from the past, Adelaide grows increasingly concerned that something bad is going to happen. Her worst fears soon become a reality when four masked strangers descend upon the house, forcing the Wilsons into a fight for survival. When the masks come off, the family is horrified to learn that each attacker takes the appearance of one of them.', 'March 22, 2019', '1670975470.jpg', '2022-12-13 16:51:10', '2022-12-13 16:51:10'),
(65, 'Godzilla vs. Kong', 'Adventure', 'Adam Wingard', 'Thomas Tull, Jon Jashni, Brian Rogers, Mary Parent, Alex Garcia, Eric McLeod', 'Terry Rossio, Michael Dougherty, Zach Shields', 'Alexander Skarsgård, Millie Bobby, Brown Rebecca, Hall Brian, Tyree Henry', 'Kong and his protectors undertake a perilous journey to find his true home. Along for the ride is Jia, an orphaned girl who has a unique and powerful bond with the mighty beast. However, they soon find themselves in the path of an enraged Godzilla as he cuts a swath of destruction across the globe. The initial confrontation between the two titans -- instigated by unseen forces -- is only the beginning of the mystery that lies deep within the core of the planet.', 'March 31, 2021', '1670975560.jpg', '2022-12-13 16:52:40', '2022-12-13 16:52:40'),
(66, 'Wendell & Wild', 'Fantasy', 'Henry Selick', 'Henry Selick, Ellen Goldsmith-Vein, Jordan Peele, Win Rosenfeld', 'Henry Selick, Clay McLeod Chapman', 'Keegan-Michael Key, Jordan Peele, Angela Bassett, Lyric Ross', 'Two demon brothers enlist the aid of Kat Elliot — a tough teen with a load of guilt — to summon them to the Land of the Living. But what Kat demands in return leads to a brilliantly bizarre and comedic adventure like no other.', 'October 28, 2022', '1670975712.jpg', '2022-12-13 16:55:12', '2022-12-13 16:55:12'),
(67, 'To All the Boys I\'ve Loved Before', 'Romance', 'Susan Johnson', 'Jordan Levin, Matthew Kaplan, Dougie Cash', 'Sofia Alvarez', 'Lana Condor, Noah Centineo, Janel Parrish, Anna Cathcart, Andrew Bachelor', 'To All the Boys is a franchise consisting of American teenage romance installments, including three feature films and a spin-off television series, based on the titular trilogy of novels written by Jenny Han.', 'August 17, 2018', '1670975851.jpg', '2022-12-13 16:57:31', '2022-12-13 16:57:31'),
(68, 'Dobaaraa', 'Mystery', 'Anurag Kashyap', 'Shobha Kapoor, Ekta Kapoor, Sunit Khetrapal, Gaurav Bose', 'Oriol Paulo', 'Taapsee Pannu, Pavail Gulati', 'In the middle of a mysterious thunderstorm, a mother saves someone\'s life, which has unexpected consequences.', 'August 19, 2022', '1670975931.jpg', '2022-12-13 16:58:51', '2022-12-13 16:58:51'),
(69, 'The Conjuring', 'Horror', 'James Wan', 'Tony DeRosa-Grund, Peter Safran, Rob Cowan', 'Chad Hayes, Carey W. Hayes', 'Vera Farmiga, Patrick Wilson, Ron Livingston, Lili Taylor', 'In 1970, paranormal investigators and demonologists Lorraine (Vera Farmiga) and Ed (Patrick Wilson) Warren are summoned to the home of Carolyn (Lili Taylor) and Roger (Ron Livingston) Perron. The Perrons and their five daughters have recently moved into a secluded farmhouse, where a supernatural presence has made itself known. Though the manifestations are relatively benign at first, events soon escalate in horrifying fashion, especially after the Warrens discover the house\'s macabre history.', 'July 15, 2013', '1670976014.jpg', '2022-12-13 17:00:14', '2022-12-13 17:00:14'),
(70, 'Gods of Egypt', 'Adventure', 'Alex Proyas', 'Basil Iwanyk, Alex Proyas', 'Matt Sazama, Burk Sharpless', 'Nikolaj Coster-Waldau, Brenton Thwaites, Chadwick Boseman, Élodie Yung', 'The survival of mankind hangs in the balance when Set (Gerard Butler), the merciless god of darkness, usurps Egypt\'s throne and plunges the prosperous empire into chaos and conflict. Hoping to save the world and rescue his true love, a defiant mortal named Bek (Brenton Thwaites) forms an unlikely alliance with the powerful god Horus (Nikolaj Coster-Waldau). Their battle against Set and his henchmen takes them into the afterlife and across the heavens for an epic confrontation.', 'February 26, 2016', '1670976103.jpg', '2022-12-13 17:01:43', '2022-12-13 17:01:43'),
(71, 'Mortal Kombat Legends: Snow Blind (2022)', 'Fantasy', 'Ethan Spaulding', 'Rick Morales, Jim Krieg', 'Ed Boon, John Tobias', 'Jordan Rodrigues, Joel McHale, Jennifer Carpenter, Patrick Seitz', 'Hellbent on taking over Earthrealm, Kano viciously attacks town after town with the aid of three cold-blooded Black Dragon mercenaries. Those who don’t submit are annihilated but one young man won’t bend the knee to Kano: Kenshi.', 'October 9, 2022', '1670976206.jpg', '2022-12-13 17:03:26', '2022-12-13 17:03:26'),
(72, 'Single All The Way', 'Romance', 'Michael Mayer', 'Joel S. Rice', 'Chad Hodge', 'Michael Urie, Philemon Chambers, Luke Macfarlane, Barry Bostwick', 'Desperate to avoid his family\'s judgment about being single, Peter persuades best friend Nick to pose as his boyfriend on a trip home for the holidays', 'December 2, 2021', '1670976307.jpg', '2022-12-13 17:05:07', '2022-12-13 17:05:07'),
(73, 'Fever Dream', 'Mystery', 'Claudia Llosa', 'Mark Johnson, Tom Williams, Claudia Llosa', 'Samanta Schweblin', 'María Valverde, Dolores Fonzi', 'A young woman lies dying far from home. A boy sits beside her. She is not his mother. He is not her child. Together, they tell a haunting story of broken souls, an invisible threat and the power and desperation of family. Based on the internationally critically acclaimed homonymous novel by Samanta Schweblin.', 'October 6, 2021', '1670976393.jpg', '2022-12-13 17:06:33', '2022-12-13 17:06:33'),
(74, 'No One Gets Out Alive', 'Horror', 'Santiago Menghini', 'Jonathan Cavendish, Will Tennant', 'Jon Croker', 'Cristina Rodlo Marc Menchaca', 'Desperate and without documentation, a woman from Mexico moves into a rundown Cleveland boarding house. Then the unsettling cries and eerie visions begin.', 'September 29, 2021', '1670976578.jpg', '2022-12-13 17:09:38', '2022-12-13 17:09:38'),
(75, 'Divergent', 'Adventure', 'Neil Burger', 'Douglas Wick, Lucy Fisher, Pouya Shahbazian', 'Veronica Roth', 'Shailene Woodley, Theo James, Ashley Judd', 'Tris Prior (Shailene Woodley) lives in a futuristic world in which society is divided into five factions. As each person enters adulthood, he or she must choose a faction and commit to it for life. Tris chooses Dauntless -- those who pursue bravery above all else. However, her initiation leads to the discovery that she is a Divergent and will never be able to fit into just one faction. Warned that she must conceal her status, Tris uncovers a looming war which threatens everyone she loves.', 'March 21, 2014', '1670976667.jpg', '2022-12-13 17:11:07', '2022-12-13 17:11:07'),
(76, 'The King\'s Daughter', 'Fantasy', 'Sean McNamara', 'James Pang Hong, Paul Currie, Wei Han, Sean McNamara, David Brookwell, Hong Pang, Evan Wang, Qingfeng Du', 'Barry Berman, James Schamus', 'Pierce Brosnan, Kaya Scodelario, Benjamin Walker, William Hurt, Rachel Griffiths', 'King Louis XIV\'s quest for immortality leads him to capture and steal a mermaid\'s life force, a move that is further complicated by his illegitimate daughter\'s discovery of the creature.', 'January 21, 2022', '1670976967.jpg', '2022-12-13 17:16:07', '2022-12-13 17:16:07'),
(77, 'Crazy, Stupid, Love', 'Romance', 'Glenn Ficarra, John Requa', 'Steve Carell, Denise Di Novi', 'Dan Fogelman', 'Steve Carell, Ryan Gosling, Julianne Moore, Emma Stone', 'Cal Weaver (Steve Carell) is living the American dream. He has a good job, a beautiful house, great children and a beautiful wife, named Emily (Julianne Moore). Cal\'s seemingly perfect life unravels, however, when he learns that Emily has been unfaithful and wants a divorce. Over 40 and suddenly single, Cal is adrift in the fickle world of dating. Enter, Jacob Palmer (Ryan Gosling), a self-styled player who takes Cal under his wing and teaches him how to be a hit with the ladies.', 'July 29, 2011', '1670977091.jpg', '2022-12-13 17:18:11', '2022-12-13 17:18:11'),
(78, 'The 8th Night', 'Horror', 'Kim Tae-hyoung', 'Hyun Kwang Seo', 'Kim Tae-hyoung', 'Lee Sung-min, Park Hae-joon, Kim Yoo-jung, Nam Da-reum', 'With prayer beads in one hand and an axe in the other, a monk hunts down a millennia-old spirit that\'s possessing humans and unleashing hell on Earth.', 'July 2, 2021', '1670977235.jpg', '2022-12-13 17:20:35', '2022-12-13 17:20:35'),
(79, 'Oblivion', 'Adventure', 'Joseph Kosinski', 'Peter Chernin, Dylan Clark, Duncan Henderson, Joseph Kosinski, Barry Levine', 'Joseph Kosinski', 'Tom Cruise, Morgan Freeman, Olga Kurylenko', 'In the year 2077, Jack Harper (Tom Cruise) works as a security repairman on an Earth left empty and devastated after a war with aliens. Jack has two weeks left before his mission ends and he joins his fellow survivors on a faraway colony. However, Jack\'s concept of reality comes crashing down after he rescues a beautiful stranger (Olga Kurylenko) from a downed spacecraft. The woman\'s arrival triggers a chain of events that culminates in Jack\'s nearly single-handed battle to save mankind.', 'April 19, 2013', '1670977392.jpg', '2022-12-13 17:23:12', '2022-12-13 17:23:12'),
(80, 'Logan', 'Action', 'James Mangold', 'Hutch Parker Simon Kinberg Lauren Shuler Donner', 'Scott Frank James Mangold Michael Green', 'Hugh Jackman, Patrick Stewart, Dafne Keen, Boyd Holbrook', 'In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.', 'February 17, 2017', '1671020625.jpg', '2022-12-14 04:23:45', '2022-12-14 04:23:45'),
(81, 'Friday', 'Comedy', 'F. Gary Gray', 'Patricia Charbonnet', 'Ice Cube DJ Pooh', 'Ice Cube, Chris Tucker, Nia Long, Tom Lister Jr.', 'It\'s Friday, and Craig and Smokey must come up with $200 they owe a local bully or there won\'t be a Saturday.', 'April 26, 1995', '1671021225.jpg', '2022-12-14 04:33:45', '2022-12-14 04:33:45'),
(82, 'Go Now', 'Drama', 'Michael Winterbottom', 'PolyGram Filmed Entertainment BBC', 'Jimmy McGovern Paul Henry Powell', 'Robert Carlyle, Juliet Aubrey, James Nesbitt, Sophie Okonedo', 'Nick, is a young Scottish soccer player living in the big city. He meets Karen, and the two fall in love and move in together. Soon after, Nick exhibits signs of serious illness.', '16 September 1995', '1671021388.jpg', '2022-12-14 04:36:28', '2022-12-14 04:36:28'),
(83, 'Fallen', 'Thriller', 'Gregory Hoblit', 'Charles Roven Dawn Steel', 'Nicholas Kazan', 'Denzel Washington, John Goodman, Donald Sutherland, Embeth Davidtz', 'Homicide detective John Hobbes witnesses the execution of serial killer Edgar Reese. Soon after the execution, the killings start again, and they are very similar to Reese\'s style..', 'January 16, 1998', '1671021537.jpg', '2022-12-14 04:38:57', '2022-12-14 04:38:57'),
(85, 'The Good, the Bad and the Ugly', 'Western', 'Sergio Leone', 'Alberto Grimaldi', 'Age & Scarpelli Luciano Vincenzoni Sergio Leone', 'Clint Eastwood, Eli Wallach, Lee Van Cleef, Aldo Giuffrè', 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', '23 December 1966', '1671022456.jpg', '2022-12-14 04:54:16', '2022-12-14 04:54:16'),
(86, 'The Avengers', 'Action', 'Joss Whedon', 'Kevin Feige', 'Joss Whedon', 'Robert Downey Jr., Chris Evans, Scarlett Johansson, Jeremy Renner', 'Earth\'s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.', 'April 11, 2012', '1671022556.jpg', '2022-12-14 04:55:56', '2022-12-14 04:55:56'),
(87, 'Ted', 'Comedy', 'Seth MacFarlane', 'Scott Stuber Seth MacFarlane John Jacobs Jason Clark', 'Seth MacFarlane Alec Sulkin Wellesley Wild', 'Mark Wahlberg, Mila Kunis, Seth MacFarlane, Joel McHale', 'John Bennett, a man whose childhood wish of bringing his teddy bear to life came true, now must decide between keeping the relationship with the bear, Ted or his girlfriend, Lori.', 'June 29, 2012', '1671022615.jpg', '2022-12-14 04:56:55', '2022-12-14 04:56:55'),
(88, 'Boyhood', 'Drama', 'Richard Linklater', 'Richard Linklater Cathleen Sutherland Jonathan Sehring John Sloss', 'Richard Linklater', 'Ellar Coltrane, Patricia Arquette, Ethan Hawke, Elijah Smith', 'The life of Mason, from early childhood to his arrival at college.', 'January 19, 2014', '1671022842.jpg', '2022-12-14 05:00:42', '2022-12-14 05:00:42'),
(89, 'The Bone Collector', 'Thriller', 'Phillip Noyce', 'Martin Bregman Michael Bregman Louis A. Stroller', 'Jeremy Iacone', 'Denzel Washington, Angelina Jolie, Queen Latifah, Michael Rooker', 'A quadriplegic ex-homicide detective and his partner try to track down a serial killer who is terrorizing New York City.', 'November 5, 1999', '1671022957.jpg', '2022-12-14 05:02:37', '2022-12-14 05:02:37');
INSERT INTO `movies` (`id`, `title`, `genre`, `director`, `producer`, `writer`, `casts`, `summary`, `release_date`, `image_path`, `created_at`, `updated_at`) VALUES
(90, 'Butch Cassidy and the Sundance Kid', 'Western', 'George Roy Hill', 'John Foreman', 'William Goldman', 'Paul Newman, Robert Redford, Katharine Ross, Strother Martin', 'Wyoming, early 1900s. Butch Cassidy and The Sundance Kid are the leaders of a band of outlaws. After a train robbery goes wrong they find themselves on the run with a posse hard on their heels. Their solution - escape to Bolivia.', 'September 23, 1969', '1671023043.jpg', '2022-12-14 05:04:03', '2022-12-14 05:04:03'),
(91, 'Captain America: The First Avenger', 'Action', 'Joe Johnston', 'Kevin Feige', 'Christopher Markus Stephen McFeely', 'Chris Evans, Hugo Weaving, Samuel L. Jackson, Hayley Atwell', 'Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a \"Super-Soldier serum\". But being Captain America comes at a price as he attempts to take down a warmonger and a terrorist organization.', 'July 19, 2011', '1671023117.jpg', '2022-12-14 05:05:17', '2022-12-14 05:05:17'),
(92, 'Zombieland', 'Comedy', 'Ruben Fleischer', 'Gavin Polone', 'Rhett Reese Paul Wernick', 'Jesse Eisenberg, Emma Stone, Woody Harrelson, Abigail Breslin', 'A shy student trying to reach his family in Ohio, a gun-toting bruiser in search of the last Twinkie and a pair of sisters striving to get to an amusement park join forces in a trek across a zombie-filled America.', 'September 25, 2009', '1671023212.jpg', '2022-12-14 05:06:52', '2022-12-14 05:06:52'),
(93, 'Pan\'s Labyrinth', 'Drama', 'Guillermo del Toro', 'Guillermo del Toro Bertha Navarro Alfonso Cuarón Frida Torresblanco Álvaro Augustin', 'Guillermo del Toro', 'Ivana Baquero, Ariadna Gil, Sergi López, Maribel Verdú', 'In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.', 'June 28, 1996', '1671023332.jpg', '2022-12-14 05:08:52', '2022-12-14 05:08:52'),
(94, 'Secret Window', 'Thriller', 'David Koepp', 'Gavin Polone Ezra Swerdlow', 'David Koepp', 'Johnny Depp, Maria Bello, John Turturro, Timothy Hutton', 'The life of Mason, from early childhood to his arrival at college.', 'March 12, 2004', '1671023411.jpg', '2022-12-14 05:10:11', '2022-12-14 05:10:11'),
(95, 'Once Upon a Time in the West', 'Western', 'Sergio Leone', 'Fulvio Morsella', 'Sergio Donati Sergio Leone', 'Henry Fonda, Charles Bronson, Claudia Cardinale, Jason Robards', 'A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.', '20 December 1968', '1671023606.jpg', '2022-12-14 05:13:26', '2022-12-14 05:13:26'),
(96, 'The Suicide Squad', 'Action', 'James Gunn', 'Charles Roven Peter Safran', 'James Gunn', 'Margot Robbie, Idris Elba, John Cena, Joel Kinnaman', 'Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.', 'July 30, 2021', '1671023699.jpg', '2022-12-14 05:14:59', '2022-12-14 05:14:59'),
(97, 'The Nutty Professor', 'Comedy', 'Tom Shadyac', 'Brian Grazer Russell Simmons', 'David Sheffield Barry W. Blaustein Tom Shadyac Steve Oedekerk', 'Eddie Murphy, Jada Pinkett Smith, James Coburn, Larry Miller', 'Grossly overweight yet good-hearted professor Sherman Klump takes a special chemical that turns him into the slim but obnoxious Buddy Love.', 'June 28, 1996', '1671023758.jpg', '2022-12-14 05:15:58', '2022-12-14 05:15:58'),
(98, 'What\'s Eating Gilbert Grape', 'Drama', 'Lasse Hallström', 'Bertil Ohlsson David Matalon Meir Teper', 'Peter Hedges', 'Johnny Depp, Leonardo DiCaprio, Juliette Lewis, Mary Steenburgen', 'A young man in a small Midwestern town struggles to care for his mentally-disabled younger brother and morbidly obese mother while attempting to pursue his own happiness.', 'December 17, 1993', '1671023871.jpg', '2022-12-14 05:17:51', '2022-12-14 05:17:51'),
(99, 'The Book of Eli', 'Thriller', 'Albert Hughes, Allen Hughes', 'Joel Silver Denzel Washington Broderick Johnson Andrew A. Kosove David Valdes', 'Gary Whitta', 'Denzel Washington, Mila Kunis, Ray Stevenson, Gary Oldman', 'A post-apocalyptic tale, in which a lone man fights his way across America in order to protect a sacred book that holds the secrets to saving humankind.', 'January 15, 2010', '1671023948.jpg', '2022-12-14 05:19:08', '2022-12-14 05:19:08'),
(100, 'McCabe & Mrs. Miller', 'Western', 'Robert Altman', 'David Foster Mitchell Brower', 'Robert Altman Brian McKay', 'Warren Beatty, Julie Christie, Rene Auberjonois, William Devane', 'A gambler and a prostitute become business partners in a remote Old West mining town, and their enterprise thrives until a large corporation arrives on the scene.', 'June 24, 1971', '1671024016.jpg', '2022-12-14 05:20:16', '2022-12-14 05:20:16'),
(101, 'Guardians of the Galaxy', 'Action', 'James Gunn', 'Kevin Feige', 'James Gunn Nicole Perlman', 'Chris Pratt, Vin Diesel, Bradley Cooper, Zoe Saldana', 'A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.', 'July 21, 2014', '1671024102.jpg', '2022-12-14 05:21:42', '2022-12-14 05:21:42'),
(102, 'The Truman Show', 'Comedy', 'Peter Weir', 'Kevin Feige', 'James Gunn Nicole Perlman', 'Jim Carrey, Ed Harris, Laura Linney, Noah Emmerich', 'An insurance salesman discovers his whole life is actually a reality TV show.', 'July 21, 2014', '1671024154.jpg', '2022-12-14 05:22:34', '2022-12-14 05:22:34'),
(103, 'Billy Elliot', 'Drama', 'Stephen Daldry', 'Greg Brenman Jon Finn', 'Lee Hall', 'Jamie Bell, Julie Walters, Jean Heywood, Jamie Draven', 'A talented young boy becomes torn between his unexpected love of dance and the disintegration of his family.', '29 September 2000', '1671024500.jpg', '2022-12-14 05:28:20', '2022-12-14 05:28:20'),
(104, 'Deja Vu', 'Thriller', 'Tony Scott', 'Jerry Bruckheimer', 'Bill Marsilii Terry Rossio', 'Denzel Washington, Paula Patton, Jim Caviezel, Val Kilmer', 'After a ferry is bombed in New Orleans, an A.T.F. agent joins a unique investigation using experimental surveillance technology to find the bomber, but soon finds himself becoming obsessed with one of the victims.', 'November 22, 2006', '1671024574.jpg', '2022-12-14 05:29:34', '2022-12-14 05:29:34'),
(105, 'Winchester \'73', 'Western', 'Anthony Mann', 'Aaron Rosenberg', 'Borden Chase Robert L. Richards', 'James Stewart, Shelley Winters, Dan Duryea, Stephen McNally', 'A cowboy\'s obsession with a stolen rifle leads to a bullet-ridden odyssey through the American West.', 'July 12, 1950', '1671024667.jpg', '2022-12-14 05:31:07', '2022-12-14 05:31:07'),
(106, 'Black Panther', 'Action', 'Ryan Coogler', 'Kevin Feige', 'Ryan Coogler Joe Robert Cole', 'Chadwick Boseman, Michael B. Jordan, Lupita Nyong\'o, Danai Gurira', 'T\'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country\'s past.', 'October 26, 2022', '1671024792.jpg', '2022-12-14 05:33:12', '2022-12-14 05:33:12'),
(107, 'Fear and Loathing in Las Vegas', 'Comedy', 'Terry Gilliam', 'Patrick Cassavetti Laila Nabulsi Stephen Nemeth', 'Terry Gilliam Tony Grisoni Alex Cox Tod Davies', 'Johnny Depp, Benicio Del Toro, Tobey Maguire, Michael Lee Gogin', 'An oddball journalist and his psychopathic lawyer travel to Las Vegas for a series of psychedelic escapades.', 'May 22, 1998', '1671024912.jpg', '2022-12-14 05:35:12', '2022-12-14 05:35:12'),
(108, 'Little Miss Sunshine', 'Drama', 'Jonathan Dayton, Valerie Faris i', 'Marc Turtletaub David T. Friendly Peter Saraf Albert Berger Ron Yerxa', 'Michael Arndt', 'Steve Carell, Toni Collette, Greg Kinnear, Abigail Breslin', 'A family determined to get their young daughter into the finals of a beauty pageant take a cross-country trip in their VW bus.', 'January 20, 2006', '1671025132.jpg', '2022-12-14 05:38:52', '2022-12-14 05:38:52'),
(109, 'Donnie Darko', 'Thriller', 'Richard Kelly', 'Sean McKittrick Nancy Juvonen Adam Fields', 'Richard Kelly', 'Jake Gyllenhaal, Jena Malone, Mary McDonnell, Holmes Osborne', 'After narrowly escaping a bizarre accident, a troubled teenager is plagued by visions of a man in a large rabbit suit who manipulates him to commit a series of crimes.', 'January 19, 2001', '1671025200.jpg', '2022-12-14 05:40:00', '2022-12-14 05:40:00'),
(110, 'The Man Who Shot Liberty Valance', 'Western', 'John Ford', 'Willis Goldbeck', 'James Warner Bellah Willis Goldbeck', 'James Stewart, John Wayne, Vera Miles, Lee Marvin', 'A senator returns to a Western town for the funeral of an old friend and tells the story of his origins.', 'April 22, 1962', '1671025259.jpg', '2022-12-14 05:40:59', '2022-12-14 05:40:59'),
(111, 'Shang-Chi and the Legend of the Ten Rings', 'Action', 'Destin Daniel Cretton', 'Kevin Feige Jonathan Schwartz', 'Dave Callaham Destin Daniel Cretton Andrew Lanham', 'Simu Liu, Awkwafina, Tony Chiu-Wai Leung, Ben Kingsley', 'Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.', 'August 16, 2021', '1671025307.jpg', '2022-12-14 05:41:47', '2022-12-14 05:41:47'),
(112, 'The Waterboy', 'Comedy', 'Frank Coraci', 'Jack Giarraputo Robert Simonds', 'Tim Herlihy Adam Sandler', 'Adam Sandler, Kathy Bates, Henry Winkler, Fairuza Balk', 'A waterboy for a college football team discovers he has a unique tackling ability and becomes a member of the team.', 'November 6, 1998', '1671025379.jpg', '2022-12-14 05:42:59', '2022-12-14 05:42:59'),
(113, 'Slumdog Millionaire', 'Drama', 'Danny Boyle, Loveleen Tandan', 'Christian Colson', 'Simon Beaufoy', 'Dev Patel, Freida Pinto, Saurabh Shukla, Anil Kapoor', 'A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of \"Who Wants to be a Millionaire?\".', '30 August 2008', '1671025458.jpg', '2022-12-14 05:44:18', '2022-12-14 05:44:18'),
(114, 'Sin City', 'Thriller', 'Frank Miller, Quentin Tarantino, Robert Rodriguez', 'Elizabeth Avellán Frank Miller Robert Rodriguez', 'Frank Miller', 'Mickey Rourke, Clive Owen, Bruce Willis, Jessica Alba', 'An exploration of the dark and miserable Basin City and three of its residents, all of whom are caught up in violent corruption.', 'March 28, 2005', '1671025531.jpg', '2022-12-14 05:45:31', '2022-12-14 05:45:31'),
(115, 'Pat Garrett & Billy the Kid', 'Western', 'Sam Peckinpah', 'Gordon Carroll', 'Rudy Wurlitzer', 'James Coburn, Kris Kristofferson, Richard Jaeckel, Katy Jurado', 'Pat Garrett is hired as a lawman on behalf of a group of wealthy New Mexico cattle barons to bring down his old friend Billy the Kid.', 'May 23, 1973', '1671025584.jpg', '2022-12-14 05:46:24', '2022-12-14 05:46:24'),
(116, 'Captain Marvel', 'Action', 'Anna Boden, Ryan Fleck', 'Kevin Feige', 'Anna Boden, Ryan Fleck', 'Brie Larson, Samuel L. Jackson, Ben Mendelsohn, Jude Law', 'Carol Danvers becomes one of the universe\'s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.', 'February 27, 2019', '1671025769.jpg', '2022-12-14 05:49:29', '2022-12-14 05:49:29'),
(117, 'American Pie', 'Comedy', 'Paul Weitz, Chris Weitz', 'Warren Zide Craig Perry Chris Moore Chris Weitz', 'Adam Herz', 'Jason Biggs, Chris Klein, Thomas Ian Nicholas, Jennifer Coolidge', 'Four teenage boys enter a pact to lose their virginity by prom night.', 'July 9, 1999', '1671025826.jpg', '2022-12-14 05:50:26', '2022-12-14 05:50:26'),
(118, 'Sorry We Missed You', 'Drama', 'Ken Loach', 'Rebecca O\'Brien', 'Paul Laverty', 'Kris Hitchen, Debbie Honeywood, Rhys Mcgowan, Katie Proctor', 'Hoping that self-employment through gig economy can solve their financial woes, a hard-up UK delivery driver and his wife struggling to raise a family end up trapped in the vicious circle of this modern- day form of labour exploitation.', '16 May 2019', '1671025879.jpg', '2022-12-14 05:51:19', '2022-12-14 05:51:19'),
(119, 'Pulp Fiction', 'Thriller', 'Quentin Tarantino', 'Lawrence Bender', 'Quentin Tarantino', 'John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'May 21, 1994', '1671025948.jpg', '2022-12-14 05:52:28', '2022-12-14 05:52:28'),
(120, 'True Grit', 'Western', 'Henry Hathaway', 'Hal B. Wallis', 'Marguerite Roberts', 'John Wayne, Kim Darby, Glen Campbell, Jeremy Slate', 'A drunken, hard-nosed U.S. Marshal and a Texas Ranger help a stubborn teenager track down her father\'s murderer in Indian Territory.', 'June 12, 1969', '1671026011.jpg', '2022-12-14 05:53:31', '2022-12-14 05:53:31'),
(121, 'June 12, 1969', 'Action', 'Cate Shortland', 'Kevin Feige', 'Eric Pearson', 'Scarlett Johansson, Florence Pugh, David Harbour, Rachel Weisz', 'Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.', 'June 29, 2021', '1671026059.jpg', '2022-12-14 05:54:19', '2022-12-14 05:54:19'),
(122, 'Bad Boys', 'Comedy', 'Michael Bay', 'Don Simpson Jerry Bruckheimer', 'Michael Barrie Jim Mulholland Doug Richardson', 'Will Smith, Martin Lawrence, Lisa Boyle, Michael Taliferro', 'Two hip detectives protect a witness to a murder while investigating a case of stolen heroin from the evidence storage room from their police precinct.', 'April 7, 1995', '1671026133.jpg', '2022-12-14 05:55:33', '2022-12-14 05:55:33'),
(123, 'Mommy', 'Drama', 'Xavier Dolan', 'Xavier Dolan Nancy Grant', 'Xavier Dolan', 'Anne Dorval, Antoine Olivier Pilon, Suzanne Clément, Patrick Huard', 'A widowed single mother, raising her violent son alone, finds new hope when a mysterious neighbor inserts herself into their household.', '22 May 2014', '1671026185.jpg', '2022-12-14 05:56:25', '2022-12-14 05:56:25'),
(124, 'Training Day', 'Thriller', 'Antoine Fuqua', 'Bobby Newmyer Jeffrey Silver', 'David Ayer', 'Denzel Washington, Ethan Hawke, Scott Glenn, Tom Berenger', 'A rookie cop spends his first day as a Los Angeles narcotics officer with a rogue detective who isn\'t what he appears to be.', 'September 2, 2001', '1671026266.jpg', '2022-12-14 05:57:46', '2022-12-14 05:57:46'),
(125, 'Django Unchained', 'Western', 'Quentin Tarantino', 'A Band Apart[1] Columbia Pictures[1]', 'Quentin Tarantino', 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington', 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.', 'December 11, 2012', '1671026310.jpg', '2022-12-14 05:58:30', '2022-12-14 05:58:30'),
(126, 'Wonder Woman', 'Action', 'Patty Jenkins', 'Charles Roven Deborah Snyder Zack Snyder Richard Suckle', 'Allan Heinberg', 'Gal Gadot, Chris Pine, Robin Wright, Lucy Davis', 'When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.', 'May 25, 2017', '1671026976.jpg', '2022-12-14 06:09:36', '2022-12-14 06:09:36'),
(127, 'Scary Movie', 'Comedy', 'Keenen Ivory Wayans', 'Eric L. Gold Lee R. Mayes', 'Shawn Wayans Marlon Wayans Buddy Johnson Phil Beauman Jason Friedberg Aaron Seltzer', 'Anna Faris, Jon Abrahams, Marlon Wayans, Carmen Electra', 'A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.', 'July 7, 2000', '1671027023.jpg', '2022-12-14 06:10:23', '2022-12-14 06:10:23'),
(128, 'Infernal Affairs', 'Drama', 'Andrew Lau, Alan Mak', 'Andrew Lau', 'Alan Mak Felix Chong', 'Andy Lau, Tony Chiu-Wai Leung, Anthony Chau-Sang Wong, Eric Tsang', 'Two married couples adjust to the vast social and economic changes taking place in China from the 1980s to the present.', '12 December 2002', '1671027094.jpg', '2022-12-14 06:11:34', '2022-12-14 06:11:34'),
(129, 'The Hateful Eight', 'Thriller', 'Quentin Tarantino', 'Richard N. Gladstein Stacey Sher Shannon McIntosh', 'Quentin Tarantino', 'Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh, Walton Goggins', 'In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.', 'December 7, 2015', '1671027146.jpg', '2022-12-14 06:12:26', '2022-12-14 06:12:26'),
(130, 'Dead Man', 'Western', 'Jim Jarmusch', 'Demetra J. MacBride', 'Jim Jarmusch', 'Johnny Depp, Gary Farmer, Crispin Glover, Lance Henriksen', 'On the run after murdering a man, accountant William Blake encounters a strange aboriginal American man named Nobody who prepares him for his journey into the spiritual world.', 'May 26, 1995', '1671027192.jpg', '2022-12-14 06:13:12', '2022-12-14 06:13:12'),
(131, 'Aquaman', 'Action', 'James Wan', 'Peter Safran Rob Cowan', 'David Leslie Johnson-McGoldrick Will Beall', 'Jason Momoa, Amber Heard, Willem Dafoe, Patrick Wilson', 'Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.', 'November 26, 2018', '1671027296.jpg', '2022-12-14 06:14:56', '2022-12-14 06:14:56'),
(132, 'Bruce Almighty', 'Comedy', 'Tom Shadyac', 'Tom Shadyac Jim Carrey[1] James D. Brubaker Michael Bostick Steve Koren Mark O\'Keefe', 'Steve Koren Mark O\'Keefe Steve Oedekerk', 'Jim Carrey, Jennifer Aniston, Morgan Freeman, Philip Baker Hall', 'A whiny news reporter is given the chance to step into God\'s shoes.', 'May 14, 2003', '1671027370.jpg', '2022-12-14 06:16:10', '2022-12-14 06:16:10'),
(133, 'So Long, My Son', 'Drama', 'Xiaoshuai Wang', 'Liu Xuan', 'A Mei Wang Xiaoshuai', 'Jingchun Wang, Mei Yong, Xi Qi, Roy Wang', 'Prison inmates form a football team to challenge the prison guards.', '14 February 2019', '1671027428.jpg', '2022-12-14 06:17:08', '2022-12-14 06:17:08'),
(134, 'The Call', 'Thriller', 'Brad Anderson', 'Jeff Graup Michael Luisi Michael A. Helfant Robert L. Stein Bradley Gallo', 'Richard D\'Ovidio', 'Halle Berry, Evie Thompson, Abigail Breslin, Morris Chestnut', 'When a veteran 911 operator takes a life-altering call from a teenage girl who has just been abducted, she realizes that she must confront a killer from her past in order to save the girl\'s life.', 'March 15, 2013', '1671027492.jpg', '2022-12-14 06:18:12', '2022-12-14 06:18:12'),
(135, '3:10 to Yuma', 'Western', 'James Mangold', 'Jeff Graup Michael Luisi Michael A. Helfant Robert L. Stein Bradley Gallo', 'Halsted Welles Michael Brandt Derek Haas', 'Russell Crowe, Christian Bale, Ben Foster, Logan Lerman', 'A small-time rancher agrees to hold a captured outlaw who\'s awaiting a train to go to court in Yuma. A battle of wills ensues as the outlaw tries to psych out the rancher.', 'August 21, 2007', '1671027621.jpg', '2022-12-14 06:20:21', '2022-12-14 06:20:21'),
(136, 'Batman Begins', 'Action', 'Christopher Nolan', 'Christopher Nolan David S. Goyer', 'Charles Roven Emma Thomas Larry Franco', 'Christian Bale, Michael Caine, Ken Watanabe, Liam Neeson', 'After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.', 'May 31, 2005', '1671027718.jpg', '2022-12-14 06:21:58', '2022-12-14 06:21:58'),
(137, 'The Longest Yard', 'Comedy', 'Peter Segal', 'Jack Giarraputo', 'Sheldon Turner', 'Adam Sandler, Burt Reynolds, Chris Rock, Nelly', 'Prison inmates form a football team to challenge the prison guards.', 'May 27, 2005', '1671027774.jpg', '2022-12-14 06:22:54', '2022-12-14 06:22:54'),
(138, 'Dearest', 'Drama', 'Peter Chan', 'Jojo Hui', 'Zhang Ji', 'Wei Zhao, Bo Huang, Dawei Tong, Lei Hao', 'A story centered around a divorced couple living in a southern Chinese city Shenzhen and dealing with the disappearance of their missing son.', '4 September 2014', '1671027827.jpg', '2022-12-14 06:23:47', '2022-12-14 06:23:47'),
(139, 'The Recruit', 'Thriller', 'Roger Donaldson', 'Jeff Apple Gary Barber Roger Birnbaum', 'Roger Towne Kurt Wimmer Mitch Glazer', 'Al Pacino, Colin Farrell, Bridget Moynahan, Gabriel Macht', 'A brilliant young CIA trainee is asked by his mentor to help find a mole in the Agency.', 'January 25, 2003', '1671027892.jpg', '2022-12-14 06:24:52', '2022-12-14 06:24:52'),
(140, 'High Noon', 'Western', 'Fred Zinnemann', 'Stanley Kramer', 'Carl Foreman', 'Gary Cooper, Grace Kelly, Thomas Mitchell, Lloyd Bridges', 'A town Marshal, despite the disagreements of his newlywed bride and the townspeople around him, must face a gang of deadly killers alone at \"high noon\" when the gang leader, an outlaw he \"sent up\" years ago, arrives on the noon train.', 'July 24, 1952', '1671027951.jpg', '2022-12-14 06:25:51', '2022-12-14 06:25:51'),
(141, '1917', 'Action', 'Sam Mendes', 'Sam Mendes Pippa Harris Jayne-Ann Tenggren Callum McDougall Brian Oliver', 'Sam Mendes Krysty Wilson-Cairns', 'Dean-Charles Chapman, George MacKay, Daniel Mays, Colin Firth', 'During World War I, two British soldiers -- Lance Cpl. Schofield and Lance Cpl. Blake -- receive seemingly impossible orders. In a race against time, they must cross over into enemy territory to deliver a message that could potentially save 1,600 of their fellow comrades', '4 December 2019', '1671028154.jpg', '2022-12-14 06:29:14', '2022-12-14 06:29:14'),
(142, 'The Bucket List', 'Comedy', 'Rob Reiner', 'Craig Zadan Neil Meron Alan Greisman Rob Reiner', 'Justin Zackham', 'Jack Nicholson, Morgan Freeman, Sean Hayes, Beverly Todd', 'Two terminally ill men escape from a cancer ward and head off on a road trip with a wish list of to-dos before they die.', 'December 15, 2007', '1671028280.jpg', '2022-12-14 06:31:20', '2022-12-14 06:31:20'),
(143, 'Lucky Number Slevin', 'Thriller', 'Paul McGuigan', 'Chris Roberts Christopher Eberts Kia Jam Andreas Grosch Anthony Rhulen Tyler Mitchell Robert Kravis', 'Jason Smilovic', 'Josh Hartnett, Ben Kingsley, Morgan Freeman, Lucy Liu', 'A case of mistaken identity lands Slevin into the middle of a war being plotted by two of the city\'s most rival crime bosses. Under constant surveillance by Detective Brikowski and assassin Goodkat, he must get them before they get him.', 'February 24, 2006', '1671028385.jpg', '2022-12-14 06:33:05', '2022-12-14 06:33:05'),
(144, 'The Outlaw Josey Wales', 'Western', 'Clint Eastwood', 'Robert Daley', 'Phil Kaufman Sonia Chernus', 'Clint Eastwood, Sondra Locke, Chief Dan George, Bill McKinney', 'Missouri farmer Josey Wales joins a Confederate guerrilla unit and winds up on the run from the Union soldiers who murdered his family.', 'June 30, 1976', '1671028434.jpg', '2022-12-14 06:33:54', '2022-12-14 06:33:54');

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `reviews`
--

CREATE TABLE `reviews` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `movie_id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `rate` decimal(10,2) NOT NULL,
  `comment_body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `reviews`
--

INSERT INTO `reviews` (`id`, `movie_id`, `user_id`, `rate`, `comment_body`, `created_at`, `updated_at`) VALUES
(1, 1, 2, '9.00', 'Very entertaining!', '2022-12-16 08:41:08', '2022-12-16 08:41:08'),
(2, 2, 1, '6.00', 'Good movie', '2022-12-16 08:42:31', '2022-12-16 08:42:31'),
(3, 3, 1, '10.00', 'It was fantastic!', '2022-12-16 08:42:56', '2022-12-16 08:42:56'),
(4, 4, 1, '5.00', 'Good movie', '2022-12-16 08:43:16', '2022-12-16 08:43:16'),
(5, 1, 1, '5.00', 'It was okay, bad CGI', '2022-12-16 08:43:34', '2022-12-16 08:43:34'),
(6, 2, 2, '7.00', 'Very entertaining!', '2022-12-16 08:44:17', '2022-12-16 08:44:17'),
(7, 3, 2, '8.00', 'Good movie', '2022-12-16 08:44:34', '2022-12-16 08:44:34'),
(8, 4, 2, '6.00', 'Very entertaining!', '2022-12-16 08:44:56', '2022-12-16 08:44:56'),
(9, 1, 4, '10.00', 'The best movie this year! Storyline was great', '2022-12-16 08:45:39', '2022-12-16 08:45:39'),
(10, 2, 4, '10.00', 'The best movie this year! Storyline was great', '2022-12-16 08:46:00', '2022-12-16 08:46:00'),
(11, 3, 4, '10.00', 'The best movie this year! Storyline was great', '2022-12-16 08:46:16', '2022-12-16 08:46:16'),
(12, 4, 4, '9.00', 'It was fantastic!', '2022-12-16 08:46:38', '2022-12-16 08:46:38'),
(13, 4, 2, '4.00', 'Good movie', '2022-12-18 08:32:31', '2022-12-18 08:32:31');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `role_as` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role_as`) VALUES
(1, 'Gwen Hidalgo', 'gwen@gmail.com', NULL, '$2y$10$THpxPGd0YuQ1ad9ZAxyrTuN6lQl9PFCzuqRiK8V316PnaVG4vVZvW', NULL, '2022-12-08 19:58:37', '2022-12-08 19:58:37', 0),
(2, 'Julie Ann Sapla', 'julie@gmail.com', NULL, '$2y$10$PS1veT/0lWlTrFa31aJUkO41AHwC4.URtXPq3yp5j7KZWWoDiGirG', NULL, '2022-12-08 19:59:28', '2022-12-08 19:59:28', 0),
(3, 'Admin', 'admin@example.com', NULL, '$2y$10$lLWl/UgDJCDc3SmZckAQY.5xhcPF97AbdI5dp4xQUxyC7XOjK1g.2', NULL, '2022-12-08 23:10:50', '2022-12-08 23:10:50', 1),
(4, 'Marc Lumba', 'marc@yahoo.com', NULL, '$2y$10$GIfoQnyD7Br1VeSc2dVAMuOdIEaJcPdJmc5g6nmgO9M6oD.d4SZU.', NULL, '2022-12-12 08:30:57', '2022-12-12 08:30:57', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`);

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `movies`
--
ALTER TABLE `movies`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Indexes for table `reviews`
--
ALTER TABLE `reviews`
  ADD PRIMARY KEY (`id`),
  ADD KEY `reviews_movie_id_foreign` (`movie_id`),
  ADD KEY `reviews_user_id_foreign` (`user_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `movies`
--
ALTER TABLE `movies`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=146;

--
-- AUTO_INCREMENT for table `reviews`
--
ALTER TABLE `reviews`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `reviews`
--
ALTER TABLE `reviews`
  ADD CONSTRAINT `reviews_movie_id_foreign` FOREIGN KEY (`movie_id`) REFERENCES `movies` (`id`),
  ADD CONSTRAINT `reviews_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
